### ISSUE TITLE
Droping nested columns

### ISSUE THREAD

**Issue by gorros** [MrPowers/spark-daria#113]
As you may know Spark does not drop column if it is nested. For example `drop("person.name")` will not work. I think it will be useful to have such functionality. I came across this solution
https://stackoverflow.com/a/39943812/4390959
But maybe we can come up with our approach, since this solution is not very clear for me yet.

**Comment by MrPowers** [comment]
@gorros added this feature 😄

**Comment by gorros** [comment]
By the way, similar functionality will be added in Spark 3.1.1

**Comment by MrPowers** [comment]
@gorros - thanks for the note.  Think @gschiavon wrote about this feature in [this blog post](https://towardsdatascience.com/spark-3-nested-fields-not-so-nested-anymore-9b8d34b00b95).  

I guess we can deprecate `dropNestedColumn` in this lib (and keep `structureSchema`).  Thoughts?
