### ISSUE TITLE
how can I get src download

### ISSUE THREAD

**Issue by yuxh** [MrPowers/spark-daria#117]
I use maven in IDEA for build, I find source code jar can not be found in mvnrepository or bintray.

**Comment by MrPowers** [comment]
@yuxh - This is unfortunately a problem I have with [my other Spark library too](https://github.com/MrPowers/spark-fast-tests/issues/50).

I tried to fix this and failed.  I will try again.  Sorry this isn't properly setup already.  Thanks for creating this issue.

**Comment by MrPowers** [comment]
This project is in Maven now, the [Scala 2.11 versions are here](https://repo1.maven.org/maven2/com/github/mrpowers/spark-daria_2.11/) and [the Scala 2.12 versions are here](https://repo1.maven.org/maven2/com/github/mrpowers/spark-daria_2.12/).  Let me know if that solves your issue!
