### ISSUE TITLE
Cannot deploy project - Spark Packages is broken

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/spark-daria#119]
I used to deploy on [Spark Packages](https://spark-packages.org/), but it's not working anymore.

I need to create a more standard deploy process for this project anyways.  Some users can't access the code: https://github.com/MrPowers/spark-daria/issues/117

I tried this in the past and failed: https://github.com/MrPowers/spark-fast-tests

I will try again.  If anyone has thoughts / experience with this, please let me know.

**Comment by MrPowers** [comment]
@manuzhang - you have any suggestions on how I should go about deploying this project directly to Maven Central with SBT?  I was looking at the gearpump `build.sbt` file and [it looks pretty complicated](https://github.com/gearpump/gearpump/blob/master/build.sbt).

Any blog posts or suggestions would be appreciated!

**Comment by nvander1** [comment]
https://github.com/xerial/sbt-sonatype

I’m going to test with this plugin later and see if it goes anywhere.

**Comment by manuzhang** [comment]
@MrPowers that's not as complicated as it looks. With the help of `sbt-sonatype` as @nvander1  mention and now GitHub actions, it should be a fluent process. We can try publishing a SNAPSHOT first.

Guess you guys are both in self-quarantine now and hope you and your families are doing well !

**Comment by nvander1** [comment]
You too Manu! I hope all is well!

Yes I totally forgot about Actions, I’ve played with it a little and it’s
really nice. Have you done much with it Manu?

**Comment by MrPowers** [comment]
@nvander1 - This project is actually setup with actions already, [see here](https://github.com/MrPowers/spark-daria/runs/517787468?check_suite_focus=true).

Here's the [GitHub Actions config file](https://github.com/MrPowers/spark-daria/blob/master/.github/workflows/master.yml).

Actions could be used to automated the deploy process, but I think the first step some `sbt deploy` command working on the first place.

**Comment by MrPowers** [comment]
This project is publishing with sbt-sonatype now, thanks!
