### ISSUE TITLE
Managing JAR files

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/spark-daria#12]
@snithish - We need to figure out a good way to manage the spark-daria JAR files, so they're easily accessible for different versions of Scala and Spark.

I'm currently uploading the spark-daria JAR files to [Spark Packages](https://spark-packages.org/package/mrpowers/spark-daria).  Spark Packages seems to upload these to [Maven](https://mvnrepository.com/artifact/mrpowers/spark-daria) somehow.  Do you think we should continue using Spark Packages or migrate to Maven?

I like how [spark-testing-base manages the JAR files in Maven](https://mvnrepository.com/artifact/com.holdenkarau/spark-testing-base_2.11).  They make it easy to access different versions of spark-testing-base for different Spark, Scala, and spark-testing-base versions.  Should we try to replicate the spark-testing-base approach?

Thanks!

**Comment by snithish** [comment]
@MrPowers I have no experience uploading JARs to Maven / Spark Packages. But I do see that some projects in Spark Packages are compiled against different versions of scala https://spark-packages.org/package/spotify/spark-bigquery . I think compiling against different versions of spark could be done too. I think mvnRepository indexes the jars, which are uploaded to any binary hosting platform. Following links from mvnRepository I was led here https://dl.bintray.com/spark-packages/maven/MrPowers/ 
Conclusion: jar being uploaded to Spark Packages or any other Central Repository does not matter. We can use spark packages and upload jars complied against different versions of scala and spark.
Hope I was clear.
