### ISSUE TITLE
Wanted to understand how can i use your this repo

### ISSUE THREAD

**Issue by pankajpkh24** [MrPowers/spark-daria#123]
Hi Sir,
Actually I have use case lets say I have two types of data source always like one will be Teradata other will be oracle like that it could be hive ,db2, Cassandra like that currently we support 8 databases.

I want to do schema comparison ie the number of columns in source and target should be matching and datatype also should be matching
For example, let's say the source is Teradata and the target is Oracle then if I compare some table then data type and kind if no of columns I have to match, if something is not matching then we will throw the error.

from your framework will be possible.
Thanks in Advance.

**Comment by MrPowers** [comment]
@pankajpkh24 - thanks for reaching out.

The [spark-fast-tests SchemaComparer](https://github.com/MrPowers/spark-fast-tests/blob/master/src/main/scala/com/github/mrpowers/spark/fast/tests/SchemaComparer.scala) should help you out.  

That's another library, so I'll close this issue.  Thanks again for the message.
