### ISSUE TITLE
Does withColumnRenamed have a hidden cost similar to the hidden cost of withColumn

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/spark-daria#127]
@manuzhang has a great article on [the hidden cost of withColumn](https://medium.com/@manuzhang/the-hidden-cost-of-spark-withcolumn-8ffea517c015).

This code isn't fully optimized by the Catalyst optimizer and isn't performant.

```scala
df.columns.foldLeft(df) { case (df, col) =>
  df.withColumn(col, df(col).cast(IntegerType))
}
```

This code is better and runs faster:

```scala
df.select(df.columns.map { col =>
  df(col).cast(IntegerType)
}: _*)
```

Does `withColumnRenamed` have the same hidden cost?

Here's how spark-daria implements the `renameColumns` method:

```scala
def renameColumns(f: String => String): DataFrame =
  df.columns.foldLeft(df)((tempDf, c) => tempDf.withColumnRenamed(c, f(c))
)
```

Should the `renameColumns` method be reimplemented with a select?  cc: @nvander1 @snithish @gorros

**Comment by nvander1** [comment]
Afaik it would have the same issue that `withColumn` does since it has to run the analyzer for each dataframe along the way.
