### ISSUE TITLE
New release soon?

### ISSUE THREAD

**Issue by colindean** [MrPowers/spark-daria#129]
I'd love to use the new `DariaWriters` in a project wherein I need to output a single CSV file. This functionality seems yet unreleased. What is the timeline for the release that will include that functionality?

**Comment by MrPowers** [comment]
@colindean - thanks for opening the issue and sorry for the delayed response.  Here's how to access the latest version of the lib:

```scala
libraryDependencies += "com.github.mrpowers" %% "spark-daria" % "0.38.2"
```

If you need anything else or have any suggestions on how we can make this library better, just let me know.  Thanks again for opening the issue.

**Comment by colindean** [comment]
Thank you! I notice that the tags aren't yet up to date on GitHub. Seems like you might need a `git push --tags` in your release process.
