### ISSUE TITLE
Issue with document link

### ISSUE THREAD

**Issue by saurabhnmishra** [MrPowers/spark-daria#26]
MrPowers,
I'm prepping up write my first spark ETL and your posts on medium blog are very helpful. I would be super excited to read the document from a working link and see how can I use spark-daria in my ETL job.

The document link is not working. 
https://mrpowers.github.io/docs/spark_daria/index.html#package

**Comment by MrPowers** [comment]
Thanks for opening this issue @saurabhnmishra!  I fixed the documentation link in this commit: https://github.com/MrPowers/spark-daria/commit/9e7817ba67812fbea390928b770dd1defa6a4d50

Let me know if you ever have any other problems and I'll fix them ASAP 😉
