### ISSUE TITLE
Feature request - range validator

### ISSUE THREAD

**Issue by tomron** [MrPowers/spark-daria#27]
Validates that the field values are with in a given range (and value geq \ gt \ leq \ lt). It is easy to implement but would be nice to wrap it in a function.
Something like - 
`validateRangeFields(Seq[Tuple(String, Numeric, Numeric, Boolean, Boolean)])`

(sorry for the poor scala syntax, I'm a scala newbie)

Where the tuple fields stands for - 
* column name
* range start
* range end
* start inclusive (false implies > check, true implies >= check)
* end inclusive (false implies > check, true implies >= check)

Thanks!

**Comment by tomron** [comment]
I truly don't remember :) but make sense I looked for something more generic

**Comment by MrPowers** [comment]
Feel free to open this back up if the details ever come back to you!
