### ISSUE TITLE
1.0 major release

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/spark-daria#43]
We should make a major release to provide users with a stable public interface.

Here's how we can get this project ready for a major release:

* Go through the entire codebase and see if any methods should be deleted
* Make sure all issues are incorporated in the project or closed
* Improve the code quality when necessary
* Make all private methods are flagged accordingly and the documentation is up-to-date
* Create a more official release process going forward

**Comment by snithish** [comment]
@MrPowers this is great, I will start on this too

**Comment by MrPowers** [comment]
The 1.0 release discussion has moved to this issue: https://github.com/MrPowers/spark-daria/issues/121
