### ISSUE TITLE
build for scala 2.12

### ISSUE THREAD

**Issue by igreenfield** [MrPowers/spark-daria#45]
Could you add build for scala 2.12

**Comment by MrPowers** [comment]
Yep, I am going to work on getting spark-fast-tests to build with Scala 2.12 first (https://github.com/MrPowers/spark-fast-tests/pull/42) and will then turn my attention to spark-daria.  I'll keep you posted ;)

**Comment by MrPowers** [comment]
@igreenfield - Hope you were able to get this working.  Feel free to reopen this if it's still not working.
