### ISSUE TITLE
Error on the published pom for 0.26.0 version

### ISSUE THREAD

**Issue by igreenfield** [MrPowers/spark-daria#46]
'repositories.repository.id' must be unique: SparkPackagesRepo -> https://dl.bintray.com/spark-packages/maven/ vs http://dl.bintray.com/spark-packages/maven/ in mrpowers:spark-daria:0.26.0

**Comment by MrPowers** [comment]
@igreenfield - Did you add this to your `pom.xml`? 

```
<dependencies>
  <!-- list of dependencies -->
  <dependency>
    <groupId>mrpowers</groupId>
    <artifactId>spark-daria</artifactId>
    <version>0.26.0</version>
  </dependency>
</dependencies>
<repositories>
  <!-- list of other repositories -->
  <repository>
    <id>SparkPackagesRepo</id>
    <url>http://dl.bintray.com/spark-packages/maven</url>
  </repository>
</repositories>
```

That's what [the Spark Packages page](https://spark-packages.org/package/mrpowers/spark-daria) is suggesting.
