### ISSUE TITLE
Couldn't find the jars at http://dl.bintray.com/spark-packages/maven/MrPowers/

### ISSUE THREAD

**Issue by rsj1308** [MrPowers/spark-daria#52]
I tried to add this as a dependency in my project but maven couldn't resolve it so i went to the url and saw there was no directory for spark-daria. The jars are not published. 
Can you please publish them soon.
Thanks !!

**Comment by rsj1308** [comment]
my bad the username was smallcase !!
closing it

**Comment by MrPowers** [comment]
@rsj1308 - I'm glad you were able to figure this out!  It's kind of annoying that Maven is case sensitive.  If you ever need any additional help, just let me know!
