### ISSUE TITLE
Version for Spark 2.4 with Scala 2.11.12?

### ISSUE THREAD

**Issue by gorros** [MrPowers/spark-daria#57]
Hi @MrPowers. I started a new Maven project with Spark 2.4 and Scala 2.11.12. Is there a corresponding build for this configuration?

**Comment by MrPowers** [comment]
@gorros - Sorry for the delayed response - I missed this issue.  Did you find what you were looking for?  I think there should be a JAR file that meets your needs in Maven :)

**Comment by gorros** [comment]
I decided to use this one 0.27.1-s_2.11. By the way, if you have time please check the discussion on #50 .
