### ISSUE TITLE
Facing issue while running through spark shell command

### ISSUE THREAD

**Issue by Premagrahan** [MrPowers/spark-daria#65]
spark-shell --packages MrPowers:spark-fast-tests:1.1.

Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: MrPowers#spark-fast-tests;1.1.3: not found]

**Comment by MrPowers** [comment]
This should work with `./spark-shell --jars pathOfjarsWithCommaSeprated`.  If for some reason that doesn't work, just let me know and I can do some more troubleshooting, thanks!
