### ISSUE TITLE
Publish into maven central

### ISSUE THREAD

**Issue by nsutcliffe** [MrPowers/spark-daria#66]
dl.bintray.com is unfortunately not accessible from many of the clients I work with. Is it possible to publish spark-daria into maven central?

**Comment by MrPowers** [comment]
@nsutcliffe - the JAR files are in Maven now, [the Scala 2.11 JARs are here](https://repo1.maven.org/maven2/com/github/mrpowers/spark-daria_2.11/) and [the Scala 2.12 JARs are here](https://repo1.maven.org/maven2/com/github/mrpowers/spark-daria_2.12/).  Thanks and let me know if you need anything else!
