### ISSUE TITLE
Spark Summit 2019

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/spark-daria#69]
Sim Simeonov: https://databricks.com/sparkaisummit/north-america/sessions-single-2019?id=24

Holden: https://databricks.com/speaker/holden-karau

Albert: https://databricks.com/speaker/albert-franzi-cros

**Comment by MrPowers** [comment]
@afranzi - I'm planning on going to your talk at the upcoming Spark Summit!  I have some ideas I want to brainstorm with you.  We should hang out!

**Comment by afranzi** [comment]
Sure! Let's grab a coffee there :) I will be glad to participate in the brainstorming!
Is there any other channel to communicate with you?

**Comment by MrPowers** [comment]
@afranzi - Yea, send me an email ([my email address is here](https://github.com/MrPowers)) and we can work out the logistics!

**Comment by MrPowers** [comment]
@afranzi - Send me your email so I can get in touch somewhere other than this GitHub thread ;)

Or we can keep nerding out on GitHub - I'm cool with that option too, haha.
