### ISSUE TITLE
can I use it with pyspark too?

### ISSUE THREAD

**Issue by mundra-aman** [MrPowers/spark-daria#70]

**Comment by gorros** [comment]
I don't think so.

**Comment by MrPowers** [comment]
@mundra-aman - There is a way to run Spark Scala functions in PySpark, but in this case, you can just use the [quinn](https://github.com/MrPowers/quinn) library that has all the same functions that spark-daria has.  Let me know how that works for you!

**Comment by MrPowers** [comment]
[quinn](https://github.com/MrPowers/quinn/) has matured and it being used by a lot of folks.  That's definitely the best best for PySpark users!
