### ISSUE TITLE
Add test coverage badge to repo

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/spark-daria#75]
Is [scoverage](https://github.com/scoverage/scalac-scoverage-plugin) the best option?

**Comment by manuzhang** [comment]
Not sure it's best but I've been using scoverage for [my project](https://github.com/gearpump/gearpump)

**Comment by MrPowers** [comment]
@manuzhang - thanks, I am going to add this.

**Comment by MrPowers** [comment]
@manuzhang - I added `sbt-scoverage` and then ran `sbt coverage` and it didn't seem to generate any output in the `target/scoverage-report` directory like I expected.  And idea what I'm missing here? https://github.com/MrPowers/spark-daria/pull/83

**Comment by manuzhang** [comment]
Try `sbt test coverageReport`

**Comment by manuzhang** [comment]
Try `sbt test coverageReport`

**Comment by MrPowers** [comment]
@manuzhang - Here's what I mentioned in the Gitter channel: "I released v0.32.0 and scoverage was causing my downstream CIs to throw this error (when spark-daria was included in other projects): https://github.com/scoverage/sbt-scoverage/issues/228  Super annoying. I set coverageEnabled := false in the spark-daria build.sbt file to fix this and did a v0.32.1 release."

I had to look all over for this message...  Forgot about Gitter ;)

**Comment by manuzhang** [comment]
@MrPowers  How is spark-daria included ? Is there a way that I can reproduce your issue ?

**Comment by MrPowers** [comment]
@manuzhang - Sorry for the delayed response.

[This commit](https://github.com/MrPowers/spark-daria/commit/3a618ac36d3e335a64d785f940dd94fb686e4a24) that sets `coverageEnabled := true` was included in the v0.32.0 release.

You should be able to reproduce this bug by including spark-daria v0.32.0 in a project and then running your test suite.  I created [a spark-stringmetric branch to demonstrate the issue](https://github.com/MrPowers/spark-stringmetric/pull/6).

I think it's important to get the test coverage badge on this project.  Let me know how we can move this forward ;)

**Comment by nvander1** [comment]
Weird bug. I bet the coverage enabled in the build file causes all of
spark-Daria to be compiled with the test instrumentation.

Le dim. 26 mai 2019 à 12:39, Matthew Powers <notifications@github.com> a
écrit :

**Comment by manuzhang** [comment]
@nvander1 Confirmed after checking out the byte code. @MrPowers Did you run `sbt clean +spDist` after `sbt test coverageReport` ? It's [recommended here](https://github.com/scoverage/sbt-scoverage/issues/128) to clean things up before publishing

**Comment by MrPowers** [comment]
I'm closing this, but would be happy to add this in the future if anyone wants it / thinks it'd be useful!
