### ISSUE TITLE
artifact name convention 

### ISSUE THREAD

**Issue by igreenfield** [MrPowers/spark-daria#76]
Why not adding the scala version to artifact name. eg: `spark-daria_2.11`

**Comment by MrPowers** [comment]
@igreenfield - thanks for opening the issue.  I am publishing this project via [Spark Packages](https://spark-packages.org/) and following all their conventions.

I tried to publish this directly to Maven and failed.  I need to figure out how [to directly publish my projects to Maven Central](https://github.com/MrPowers/spark-fast-tests/issues/50).

Is this something you're experienced in?  Perhaps we can collaborate?

**Comment by igreenfield** [comment]
@MrPowers  I can help you to integrate with [travis](https://github.com/marketplace/travis-ci/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW43MA==#pricing-and-setup)

**Comment by MrPowers** [comment]
@igreenfield - thanks for offering to help.  I am going to work with @nvander1 on determining if I will be using SBT on this project going forward or if I'll switch to Mill.

After I determine the build tool, I'll figure out how to publish directly to Maven Central.  I will make sure the artifact name / POM file are following all best practices when this is getting published to Maven Central.

Sorry this isn't properly following conventions yet.  I'll try to get this sorted out ASAP.

**Comment by igreenfield** [comment]
What the status?

**Comment by MrPowers** [comment]
@igreenfield - I updated this and made it standard, thanks!  Appreciate the feedback!
