### ISSUE TITLE
duplicate repo entries in pom file

### ISSUE THREAD

**Issue by igreenfield** [MrPowers/spark-daria#77]
when using latest version:
Errors occurred while build effective model from C:\Users\igreenfield\.gradle\caches\modules-2\files-2.1\mrpowers\spark-daria\0.31.0-s_2.11\c12b7d34b6165a7ad5de127edb9259fc094f3ae2\spark-daria-0.31.0-s_2.11.pom:
    'repositories.repository.id' must be unique: SparkPackagesRepo -> https://dl.bintray.com/spark-packages/maven/ vs http://dl.bintray.com/spark-packages/maven/ in mrpowers:spark-daria:0.31.0-s_2.11

and in the pom file I see:
```
<repositories>
        <repository>
            <id>SparkPackagesRepo</id>
            <name>Spark Packages Repo</name>
            <url>https://dl.bintray.com/spark-packages/maven/</url>
            <layout>default</layout>
        </repository>
        <repository>
            <id>SparkPackagesRepo</id>
            <name>Spark Packages Repo</name>
            <url>http://dl.bintray.com/spark-packages/maven/</url>
            <layout>default</layout>
        </repository>
    </repositories>
```

**Comment by nsutcliffe** [comment]
I see this too

**Comment by igreenfield** [comment]
Can you fix this, please?

**Comment by MrPowers** [comment]
@igreenfield - This project used to follow the Spark Packages publishing process, which created all sorts of problems.

It now follows a standard publishing process and should allow for standard POM access.  See [the Scala 2.12 JARs here](https://repo1.maven.org/maven2/com/github/mrpowers/spark-daria_2.12/) for example.

I'm going to close this for now, but feel free to reopen it if this is still a problem.  Thanks for reporting this.
