### ISSUE TITLE
Add higher order functions to Scala API

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/spark-daria#85]
Do this: https://github.com/apache/spark/pull/24232

@nvander1 - want to submit a PR for this one? cc: @manuzhang 

We chatted about this work here: https://github.com/MrPowers/spark-daria/pull/80#issuecomment-491819933

**Comment by nvander1** [comment]
Yeah we’ll need to set up cross builds for this though so we only do the
backports for custom expressions in pre 2.4 spark. Otherwise it should
point to the existing implementations in spark

Le mer. 15 mai 2019 à 18:36, Matthew Powers <notifications@github.com> a
écrit :

**Comment by nvander1** [comment]
That will also affect the names of artifacts you’ll publish when we set up
maven stuff

**Comment by MrPowers** [comment]
We don't need these anymore now that they've been added to the Spark API as native functions.
